---
# This playbook will apply a specified PSU to a newly installed FMW_HOME


- name: Unzip PSU
  unarchive:
    remote_src: yes
    src: '{{ psu_zip }}'
    dest: '{{ psu_zip | dirname }}'
    creates: "{{ psu_zip | dirname }}/{{ psu_zip | basename | regex_replace('(p)([0-9]*)(_[0-9].*zip)', '\\2') }}"


- name: OPatch apply PSU
  shell: "{{ fmw_home }}/OPatch/opatch apply -silent"
  args:
    chdir: "{{ psu_zip | dirname }}/{{ psu_zip | basename | regex_replace('(p)([0-9]*)(_[0-9].*zip)', '\\2') }}"
